services:
  discord-bot:
    build: .
    image: zammad-kc-discord-bot:latest
    container_name: zammad-discord-bot
    restart: unless-stopped
    env_file: .env
    ports:
      - "3100:3100"
    volumes:
      - ./data:/app/data
    networks:
      - default
      - zammad

networks:
  zammad:
    external: true
    name: zammad-kc_default
