apiVersion: v1
kind: Service
metadata:
  name: zammad-discord-bot
  labels:
    app: zammad-discord-bot
spec:
  selector:
    app: zammad-discord-bot
  ports:
    - port: 3100
      targetPort: http
      protocol: TCP
      name: http
